### ISSUE TITLE
AUX2 incorrect

### ISSUE THREAD

**Issue by ve3rx** [m1dst/SO2Rduino#1]
?AUX2 returns the value in AUX1. This is because the code that returns aux2 value is looking at the aux1 variable by mistake in the code. Simply change the section in the Do Command for ?AUX2 to use the aux2 variable, not aux1. This fixes this issue.
Compiled and tested ok afterwards

**Comment by m1dst** [comment]
Good spot.  Did I fix it everywhere you spotted it?

**Comment by ve3rx** [comment]
I only fixed it in the do command section of my code, where it responds to the 
?AUX2 command. Testing it on a standalone Nano, it now returns the 
proper values for each aux1 and aux2 as stored in the program. Before, ?AUX2 always returned aux1 value.
I do not have the box built yet, just testing the code on a standalone Nano. With no inputs, I do get some strange results for TX1 turning on a relay (D13 - Nano LED which is RX2 relay), but I attribute that to floating inputs (no RX1/RX2 switch yet). But, this behavior is reproducible as well, will have to look into it once I breadboard the Nano with proper inputs.

Not sure how all this Github stuff works, just signed up. I assume the author will fix this in the code?
Date: Mon, 20 Jun 2016 10:06:51 -0700

**Comment by m1dst** [comment]
I am doing my best to fix issues reported but I am not the author and have
never even built the item.  I just didn't want the project to die so I have
hosted and maintained it in a limited capacity.

If you find other issues, please let me know.

**Comment by ve3rx** [comment]
Will do. I'm not a C programmer, unfortunately, so finding other faults, if any, may be tricky. However, if any weird issues shows up, I will list it.
I can follow Fortran, Basic and even assembler, but C eludes me to this day...

Steve

Date: Mon, 20 Jun 2016 10:22:12 -0700

**Comment by m1dst** [comment]
Any reported issues are better than none so everyone will benefit.  Thanks
for your support.  Maybe one day I will get around to building one but I
have a Microham U2R at present so there was never the need.
